# Generated by Django 3.0.2 on 2020-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('doubt', models.CharField(default='', max_length=5000)),
                ('image', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
